### ISSUE TITLE
most current ld64 ppc for 10.5?

### ISSUE THREAD

**Issue by kencu** [michaelweiser/ld64#1]
Hi,

I'm also hoping to get clang-3.8+ running on 10.5PPC, with some success so far. I have it installed and compiling working executables, but there are a few remaining potholes that I know about, and probably more I don't know about yet.

Your ld64 ppc project could be helpful! I'd like to integrate it into the MacPorts ld64 Portfile system to make it part of MacPorts. Of the ld64 branches you have here, would you say that 241.9-ppc-feat is the most up to day workable version to install? Or is the 264.3.102-ppc version in a finished form to use?

**Comment by michaelweiser** [comment]
Hi Ken,

IIRC I had version 241.9-ppc-feat actually running on ppc and creating working executables with llvm-3.4.1. Newer versions are mostly untested: I cherry-picked the patches over, resolved conflicts, made it compile on x86_64 and successfully tried them on some ppc object files. But since changes to ld64 and cctools are very, very small between versions, chances are very good that the current versions will work as well.

Also note that Gentoo Prefix for OS X has a very extensive patchset for ld64 and cctools in package binutils-apple. Until recently this included those ppc patches. See there for reference and inspration: https://packages.gentoo.org/packages/sys-devel/binutils-apple.

ppc support is included up until 7.3.1. For 8.2+ I dropped them because I had to admit that my efforts to get that stuff working on ppc are stalled: https://archives.gentoo.org/gentoo-alt/message/04ca30e36b6ca3639d800bb5218deef7.

There's also patches to compile using gcc-4 up until version 7.0 which might be helpful for bootstrapping on 10.5. Newer versions (ld64-253.3+) require a C++11-capable compiler.

Please drop me a line when you have working patches and bootstrap procedure for llvm on ppc. I might just give it another go with Gentoo Prefix as well. :)

Best of luck,
Micha

**Comment by kencu** [comment]
Thanks. I'll see if I can get ld64 241.9-ppc-feat working as a MacPorts portfile. That's pretty recent, and will handle the clang-3.9 objects when/if I can manage to get that working. ld64-127 that MacPorts supplies now seems OK with the clang-3.8 objects.

I have more-or-less workable versions of llvm-3.4 to 3.9 on 10.5 PPC now, and clang-3.7 and 3.8 also work. I built most of these using gcc6, although some of the dependencies (libc++, libc++ abi, and a few more) I built on 10.5 Intel with PPC slices and moved over as per the instructions here <https://trac.macports.org/wiki/LibcxxOnOlderSystems>.

There's some info on how I did it here <https://trac.macports.org/ticket/53184>, a small workaround that is currently needed to install clang-3.8 here <https://trac.macports.org/ticket/54242>, and an example of the bugs remaining here: <https://bugs.llvm.org/show_bug.cgi?id=33108>.

I have the MacPorts portfile and patch set I used to install llvm-3.8 and clang-3.8 here <https://github.com/kencu/LeopardPorts/tree/master/lang/llvm-3.8>. There is a little extra stuff in the powerpc section as I was trying to automatically work around the <ticket/54242> issue mentioned above.

At present, clang-3.8 can produce workable executables for software that requires c++11  on PPC, but there are remaining bugs in va_args that are doubles, and exceptions (and maybe more). - K
